# Generated by Django 5.0.6 on 2024-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_orders_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(default='PAID', max_length=20),
        ),
    ]
